global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Canary Feature Flag System services
  - job_name: 'canary-metrics'
    static_configs:
      - targets: ['host.docker.internal:9091']
    scrape_interval: 5s
    metrics_path: /metrics

  - job_name: 'canary-evaluation-service'
    static_configs:
      - targets: ['host.docker.internal:8081']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s

  - job_name: 'canary-control-plane'
    static_configs:
      - targets: ['host.docker.internal:8080']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']